vpc_cidr_block           = "10.0.0.0/16"
public_subnet_1_cidr     = "10.0.1.0/24"
public_subnet_2_cidr     = "10.0.2.0/24"
private_subnet_1_cidr    = "10.0.3.0/24"
private_subnet_2_cidr    = "10.0.4.0/24"
repo_name_1              = "Patient_repo"
repo_name_2              = "appointment_repo"
alb_sg_name              = "usecase8_alb_sg"
app_sg_name              = "usecase8_app_sg"
tg_name_patient          = "patient_tg"
tg_name_appoinment       = "appoinment_tg"
alb_name                 = "usecase8_alb"

